  version: "3.8"
  
  services:
  
  cirrus:
    image: "tensorworks/buccaneerdemo-cirrus"
    container_name: cirrus
    network_mode: "host"

  statsserver:
    image: "tensorworks/buccaneerdemo-statsserver"
    container_name: stats
    network_mode: "host"

  eventsserver:
    image: "tensorworks/buccaneerdemo-eventsserver"
    container_name: events
    network_mode: "host"
    volumes:
    - "eventslogs:/app"

  prometheus:
    image: "prom/prometheus"
    container_name: prometheus
    network_mode: "host"
    volumes:
    - "../../Configs/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: "host"
    volumes:
    - "../../Configs/grafana-dashboard-config.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboard-config.yaml"
    - "../../Configs/grafana-datasource-config.yaml:/etc/grafana/provisioning/datasources/grafana-datasource-config.yaml"
    - "../../Dashboards/:/etc/dashboards"

  loki:
    image: grafana/loki
    container_name: loki
    network_mode: "host"
    volumes:
    - "../../Configs/loki-local-config.yaml:/etc/loki/loki-local-config.yaml"

  promtail:
    image: grafana/promtail
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-local-config.yaml
    network_mode: "host"
    volumes:
    - "../../Configs/promtail-local-config.yaml:/etc/promtail/promtail-local-config.yaml"
    - "eventslogs:/EventsServer"

volumes:
  eventslogs:
