version: "3.8"
services:
  cirrus:
    image: "tensorworks/buccaneerdemo-cirrus"
    container_name: cirrus

  statsserver:
    image: "tensorworks/buccaneerdemo-statsserver"
    container_name: stats

  eventsserver:
    image: "tensorworks/buccaneerdemo-eventsserver"
    container_name: events
    volumes:
      - "eventslogs:/app"

  prometheus:
    image: "prom/prometheus"
    container_name: prometheus
    volumes:
      - "/root/Buccaneer/Configs/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - "/root/Buccaneer/Configs/grafana-dashboard-config.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboard-config.yaml"
      - "/root/Buccaneer/Configs/grafana-datasource-config.yaml:/etc/grafana/provisioning/datasources/grafana-datasource-config.yaml"
      - "/root/Buccaneer/Dashboards/:/etc/dashboards"

  loki:
    image: grafana/loki
    container_name: loki
    volumes:
      - "/root/Buccaneer/Configs/loki-local-config.yaml:/etc/loki/loki-local-config.yaml"

  promtail:
    image: grafana/promtail
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-local-config.yaml
    volumes:
      - "/root/Buccaneer/Configs/promtail-local-config.yaml:/etc/promtail/promtail-local-config.yaml"
      - "eventslogs:/EventsServer"

volumes:
  eventslogs:
 
 
networks:
  - loki
